{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_utilization_memory) / sum(nvidia_device_count)"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_gpu",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_memory",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(nvidia_device_count)" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_temperatures",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_power_usage",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nvidia_fanspeed", "legendFormat": "{{kubernetes_pod_node_name}}" }
   ]
  },
  {
   "title": "Driver Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    { "expr": "nvidia_driver_info" }
   ]
  }
 ]
}