#!/bin/bash

set -e

#!/bin/bash

usage() { echo "Usage: $0 [-t <oracle|hive>] [-q <query>] [-o <path for outfile>]" 1>&2; exit 1; }

while getopts ":t:q:o:" flag; do
    case "${flag}" in
        t)
            t=${OPTARG}
            ;;
        q)
            q=${OPTARG}
            ;;
        o)
            o=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${t}" ] || [ -z "${q}" ] || [ -z "${o}" ]; then
    usage
fi

echo "t = ${t}"
echo "q = ${q}"
echo "o = ${o}"


java -cp /etc/datalake JdbcClient ${t} "${q}" ${o}