FROM gitlab/gitlab-ce:11.9.4-ce.0

# Configure environment
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update && \
    apt-get install -y \
        net-tools \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 443 80 22

# Add fonts for NHN fonts
COPY fonts/ /usr/share/fonts/

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID

