{
 "title": "GPUs",
 "description": "Dashboard to get an overview of GPUs fof one server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   },
   {
    "name": "gpu",
    "query": "label_values(dcgm_gpu_temp{instance=~\"$server\"},gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (gpu) (irate(dcgm_gpu_utilization{instance=\"$server\"}[5m])) )",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"} - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{instance=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "GPU frame buffer usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(dcgm_fb_used{gpu=\"$gpu\",instance=\"$server\"} / (dcgm_fb_free{gpu=\"$gpu\",instance=\"$server\"} + dcgm_fb_used{gpu=\"$gpu\",instance=\"$server\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "GPU temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "dcgm_gpu_temp{gpu=\"$gpu\",instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}