FROM rocker/geospatial

RUN  apt-get update --fix-missing && apt-get install unixodbc unixodbc-dev --install-suggests && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY clouderahiveodbc_2.5.25.1020-2_amd64.deb /data/hiveodbc.deb
RUN dpkg -i /data/hiveodbc.deb && cp /opt/cloudera/hiveodbc/lib/64

ENV ODBCINI=/etc/odbc.ini
ENV ODBCINST=/etc/odbcinst.ini
ENV CLOUDERAHIVEINI=/etc/cloudera.hiveodbc.ini

EXPOSE 8787