ARG DEVICE_TYPE=gpu
ARG VERSION
FROM sorididim11/bdtf-lab-$DEVICE_TYPE:$VERSION

ARG VERSION
ARG DEVICE_TYPE
LABEL version=$VERSION device-type=$DEVICE_TYPE

USER $NB_UID

RUN  conda install memory_profiler==0.54  && \
    conda clean -tipsy && \
    pip install --quiet --no-cache-dir ipython_memory_usage==1.1 nbresuse==0.3.0 
    
USER $NB_UID