FROM sorididim11/spark-lab:cpu

USER $NB_UID

RUN conda install --yes -c r \
        r-essentials \
        r-acepack \
        r-aer \
        r-afex \
        && \
    conda clean -tipsy


RUN R -e "install.packages(c('odbc', \ 
                             'stargazer', \
                             'DataExplorer', \
                             'AER'), \
                             repos='http://cran.us.r-project.org')"
