FROM openjdk:8-jre

COPY jdbc-cli /usr/local/bin
COPY datalake.properties /etc/datalake.properties

RUN chmod 755 /usr/local/bin/jdbc-cli && chmod 777 /etc/datalake.properties

ENTRYPOINT [ "jdbc-cli" ]