ARG  DEVICE_TYPE=gpu
ARG  BASE_VERSION
FROM shcardbdp/mllight-lab-$DEVICE_TYPE:$BASE_VERSION
# FROM shcardbdp/dl-base-$DEVICE_TYPE:$BASE_VERSION

ARG   VERSION
ARG   DEVICE_TYPE
LABEL version=$VERSION device-type=$DEVICE_TYPE

# USER root

# # Configure environment
# ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
# ENV CONDA_DIR /opt/conda 
# ENV PATH $CONDA_DIR/bin:$PATH
# ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH

USER $NB_UID

# Install conda as jovyan and check the md5 sum provided on the download site
# ENV MINICONDA_VERSION 4.3.30
# LABEL MINICONDA=$MINICONDA_VERSION
# RUN cd /tmp && \
#     wget --quiet https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
#     echo "0b80a152332a4ce5250f3c09589c7a81 *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \
#     /bin/bash Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
#     rm Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
#     $CONDA_DIR/bin/conda config --system --prepend channels conda-forge && \
#     $CONDA_DIR/bin/conda config --system --set auto_update_conda false && \
#     $CONDA_DIR/bin/conda config --system --set show_channel_urls true && \
#     $CONDA_DIR/bin/conda update --all --quiet --yes && \
#     conda clean -tipsy && \
#     echo "export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> /home/$NB_USER/.bashrc && \
#     echo "export PATH=$JAVA_HOME/bin:$ORACLE_HOME/bin:$PATH" >> /home/$NB_USER/.bashrc && \
#     rm -rf /home/$NB_USER/.cache/yarn && \
#     fix-permissions $CONDA_DIR && \
#     fix-permissions /home/$NB_USER

# ADD connector/dbi.py /opt/conda/lib/python3.6/site-packages/shcard/    

# Install Jupyter Notebook and Hub
# pytorch requires cudatoolkit and cudnn to be installed
# RUN conda install --quiet --yes \
#         jupyter \
#         notebook \    
#         jupyterlab \
#     && conda clean -tipsy && \        
#     rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
#     rm -rf /home/$NB_USER/.cache/yarn && \
#     fix-permissions $CONDA_DIR && \
#     fix-permissions /home/$NB_USER

# ==================================================================
# Hive/impala, odbc connector
# ------------------------------------------------------------------
# RUN conda install --yes --quiet  \
#         thrift \
#         thrift_sasl \
#         impyla==0.14.1 \
#         && \
#     conda clean -tipsy && \
#     rm -rf /home/$NB_USER/.cache/yarn && \
#     fix-permissions $CONDA_DIR && \
#     fix-permissions /home/$NB_USER

# RUN pip install --quiet --no-cache-dir \
#         thriftpy \
#         pyodbc==4.0.25 \
#         cufflinks==0.14.6 \
#     && \
#     rm -rf /home/$NB_USER/.cache/yarn 

# # Add fonts for NHN fonts
# COPY fonts/ /usr/share/fonts/

# R-NOTEBOOK 
RUN conda install --yes -c r \
        r-essentials \
        r-suppdists \        
        r-zip \
        r-xfun \
        r-webshot \
        r-utf8 \
        r-uroot \
        r-tkrplot \
        r-tkrgl \
        r-tinytex \
        r-timeseries \
        r-x13binary \
        r-acepack \
        r-adgoftest \
        r-anomalydetection \
        r-ape \
        r-argparse \
        r-assertthat \
        r-backports	\
        r-base64enc \
        r-bcp \
        r-bdsmatrix \
        r-bestglm \
        r-bh \
        r-bindr \
        r-bindrcpp \
        r-bit \
        r-bit64 \
        r-bitops \
        r-blob \
        r-boot \
        r-bradleyterry2	\
        r-brew \
        r-brglm	\
        r-broom	\
        r-cairo \
        r-car \
        r-caret	\
        r-catools \
        r-cellranger \
        r-checkmate	\
        r-chron \
        r-class \
        r-cluster \
        r-coda \
        r-codetools \
        r-coin \
        r-colorspace \
        r-commonmark \
        r-config \
        r-copula \
        r-crayon \
        r-crosstalk \
        r-ctv \
        r-curl \
        r-cvst \
        r-cvtools \
        r-data.table \
        r-dbi \
        r-dbplyr \
        r-ddalpha \
        r-debugme \
        r-deoptimr \
        r-desc \
        r-devtools \
        r-diagrammer \
        r-dichromat \
        r-digest \
        r-dimred \
        r-domc \
        r-doparallel \
        r-downloader \
        r-dplyr \
        r-drr \
        r-dygraphs \
        r-e1071	\     
        r-estimability \   
        r-evaluate \
        r-feather \
        r-findpython \
        r-forcats \
        r-foreach \
        r-forecast \
        r-foreign \
        r-formatr \
        r-formattable \
        r-formula	\
        r-fracdiff	\
        r-functional	\
        r-fwdselect	\
        r-gdata	\
        r-getopt	\
        r-ggplot2	\
        r-ggvis	\
        r-gistr \
        r-git2r \
        r-glmnet	\
        r-glue	\
        r-gmp	\
        r-gower	\
        r-gplots	\
        r-gridbase	\
        r-gridextra	\
        r-grpreg	\
        r-gsl	\
        r-gsw	\
        r-gtable	\
        r-gtools	\
        r-haven	\
        r-hexbin	\
        r-highcharter	\
        r-highr	\
        r-hmisc	\
        r-hms	\
        r-htmltable	\
        r-htmltools	\
        r-htmlwidgets	\
        r-httpuv	\
        r-httr	\
        r-hunspell \
        r-igraph	\
        r-influencer	\
        r-inline	\
        r-ipred	\
        r-irdisplay	\
        r-irlba	\
        r-iterators	\
        r-janeaustenr	\
        r-jpeg	\
        r-jsonlite	\
        r-kernlab	\
        r-kernsmooth	\
        r-knitr	\
        r-kohonen	\
        r-labeling	\
        r-lahman	\
        r-lars	\
        r-lattice	\
        r-latticeextra	\
        r-lava	\
        r-lazyeval	\
        r-leaflet	\
        r-leaps	\
        r-lintr	\
        r-lme4	\
        r-lmertest	\
        r-lmtest	\
        r-logging	\
        r-lsmeans	\
        r-lubridate	\
        r-magrittr	\
        r-manipulate	\
        r-mapproj	\
        r-maps	\
        r-maptools	\
        r-markdown	\
        r-mass	\
        r-matrix	\
        r-matrixmodels	\
        r-memoise	\
        r-mgcv	\
        r-microbenchmark	\
        r-mime	\
        r-miniui	\
        r-minqa	\
        r-mlmrev	\
        r-mnormt	\
        r-modelmetrics	\
        r-modelr	\
        r-modeltools	\
        r-mongolite	\
        r-multcomp	\
        r-munsell	\
        r-mvtnorm	\
        r-networkd3	\
        r-nlme	\
        r-nloptr	\
        r-nlp	\
        r-nmf	\
        r-nnet	\
        r-numderiv	\
        r-nycflights13	\
        r-oce	\
        r-odbc	\
        r-openssl	\
        r-packrat	\
        r-pbdzmq	\
        r-pbkrtest	\
        r-pcapp	\
        r-perm	\
        r-pkgconfig	\
        r-pkgmaker	\
        r-pki	\
        r-plm	\
        r-plogr	\
        r-plyr	\
        r-png	\
        r-polspline	\
        r-praise	\
        r-proc	\
        r-processx	\
        r-prodlim	\
        r-profilemodel	\
        r-profvis	\
        r-proto	\
        r-pryr	\
        r-pspline	\
        r-psych	\
        r-purrr	\
        r-quadprog	\
        r-quantmod	\
        r-quantreg	\
        r-qvcalc	\
        r-r.methodss3	\
        r-r.oo	\
        r-r.utils	\
        r-r6	\
        r-randomforest	\
        r-rappdirs	\
        r-raster	\
        r-rbokeh	\
        r-rcolorbrewer \
        r-rcpp	\
        r-rcpparmadillo	\
        r-rcppeigen	\
        r-rcpproll	\
        r-rcurl	\
        r-readr	\
        r-readxl	\
        r-recipes	\
        r-recommended	\
        r-registry	\
        r-rematch	\
        r-repr	\
        r-reshape	\
        r-reshape2	\
        r-reticulate	\
        r-rex \
        r-rgexf	\
        r-rgl	\
        r-rhive	\
        r-rjava	\
        r-rjdbc	\
        r-rjson	\
        r-rjsonio	\
        r-rlang	\
        r-rlist	\
        r-rmarkdown	\        
        r-rms	\
        r-rngtools	\
        r-robustbase	\
        r-rocr	\
        r-rodbc	\
        r-rook	\
        r-roxygen2	\
        r-rpart	\
        r-rprojroot	\
        r-rsconnect	\
        r-rserve	\
        r-rsqlite	\
        r-rstan	\
        r-rversions	\
        r-rvest	\
        r-rzmq	\
        r-sandwich	\
        r-scales	\
        r-seacarb	\
        r-selectr	\
        r-sf	\
        r-sfsmisc	\
        r-shiny	\
        r-shinybs	\
        r-shinycssloaders	\
        r-shinydashboard	\
        r-shinyjs	\
        r-shinysky	\
        r-shinythemes	\
        r-slam	\
        r-snowballc	\
        r-sourcetools	\
        r-sp	\
        r-sparklyr	\
        r-sparsem	\
        r-spatial	\
        r-stabledist	\
        r-stanheaders	\
        r-stringdist	\
        r-stringi	\
        r-stringr	\
        r-strucchange	\
        r-survival	\
        r-tensorflow	\
        r-testit	\
        r-testthat	\
        r-tfruns	\
        r-th.data	\
        r-threejs	\
        r-tibble	\
        r-tidyr	\
        r-tidyselect	\
        r-tidytext	\
        r-tidyverse	\
        r-tilegramsr	\
        r-timedate	\
        r-tm	\
        r-tokenizers	\
        r-tseries	\
        r-ttr	\
        r-udunits2	\
        r-units	\
        r-urca	\
        r-uuid	\
        r-vars	\
        r-vgam	\
        r-viridis	\
        r-viridislite	\
        r-visnetwork	\
        r-weatherdata	\
        r-whisker	\
        r-withr	\
        r-xlsx	\
        r-xlsxjars	\
        r-xml	\
        r-xml2	\
        r-xtable	\
        r-xts	\
        r-yaml	\
        r-zoo	\
        rpy2	\
        rpy2	\
        r-aer \
        r-afex \
        && \
    conda install --yes -c conda-forge r-keras \
    && \
    conda clean -tipsy

RUN Rscript -e "install.packages(c('h2o', 'stargazer', 'DataExplorer', 'scorecard'), repos='http://cran.us.r-project.org',  lib='/opt/conda/lib/R/library')"
# RUN Rscript -e "install.packages(c('scorecard', 'stargazer', 'DataExplorer'), repos='http://cran.us.r-project.org',  lib='/opt/conda/lib/R/library')"

USER root

# RUN  if [ "$DEVICE_TYPE" = "gpu" ] ; then ln -s /usr/local/cuda-9.0/lib64/libcurand.so.9.0 /usr/local/cuda-9.0/lib64/libcurand.so.8.0 ; fi
# # Set up our notebook config.
# # COPY  jupyter/mllight/jupyter_notebook_config.py /etc/jupyter/
# COPY  jupyter/spark/jupyter_notebook_config.py /etc/jupyter/
# COPY  notebooks /home/$NB_USER/notebooks/samples/
# COPY  run_jupyter.sh /usr/local/bin/
# RUN rm -rf /home/$NB_USER/work && chown -R $NB_USER:$NB_UID /home/$NB_USER/notebooks && \
#     fix-permissions /etc/jupyter/ && fix-permissions /home/$NB_USER/notebooks/samples

EXPOSE 54321

CMD [ "/usr/local/bin/run_jupyter.sh", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token="]

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID

