FROM 17123e83675a

RUN  apt-get update --fix-missing && apt-get install -y default-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH      $PATH:$JAVA_HOME/bin

COPY cloudera/HiveJDBC41.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext
COPY cloudera/ImpalaJDBC41.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext